### ISSUE TITLE
PHP 8 Compatibility: __wakeup() must be public

### ISSUE THREAD

**Issue by dd32** [xibodevelopment/backupwordpress#1210]
### Description of issue
PHP8 is being released on Nov 26th, this plugin declares `__wakeup()` methods as private which causes a PHP warning in PHP8.

### Steps to recreate issue
1. Install PHP 8
2. Run `php -l $file`.

### Current behavior
```
php -l classes/class-path.php
  PHP Warning: The magic method HM\BackUpWordPress\Path::__wakeup() must have public visibility on line 57

php -l classes/class-notices.php
  PHP Warning: The magic method HM\BackUpWordPress\Notices::__wakeup() must have public visibility on line 46

php -l classes/class-extensions.php
  PHP Warning: The magic method HM\BackUpWordPress\Extensions::__wakeup() must have public visibility on line 35
```

**Comment by madvik** [comment]
Same problem !

**Comment by uaibo** [comment]
I am still getting this error after switching to PHP8.0

```Fatal error: Uncaught Error: Call to undefined function HM\BackUpWordPress\disk_free_space()```

it doesn't see to call the core php function but instead it thinks it is calling the ```disk_free_space()``` function within the ```HM\BackUpWordPress\``` namespace.

I have temporarily fixed it by checking the function exists but you need to find a permanent fix on the next update so that it doesn't break sites.

```if( !function_exists('@disk_free_space') ){
    return false;
}```
